/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/architecture/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all system components
         * @description Returns a list of all system components with their health status and metrics
         */
        get: operations["getComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/architecture/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component by ID
         * @description Returns detailed information about a specific component including recent events
         */
        get: operations["getComponentById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Component: {
            /**
             * @description Unique identifier for the component
             * @example core-substrate-hive-mind
             */
            id: string;
            /**
             * @description Human-readable name of the component
             * @example Hive Mind
             */
            name: string;
            /**
             * @description Architectural tier of the component
             * @example core-substrate
             * @enum {string}
             */
            tier: "core-substrate" | "core-services" | "infrastructure";
            /**
             * @description Current operational status
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "down";
            /**
             * Format: float
             * @description Health percentage (0-100)
             * @example 98.5
             */
            health: number;
            metrics: components["schemas"]["ComponentMetrics"];
            /**
             * @description List of component IDs this component depends on
             * @example [
             *       "core-substrate-context-engine",
             *       "infrastructure-postgres"
             *     ]
             */
            dependencies: string[];
        };
        ComponentMetrics: {
            /**
             * Format: float
             * @description Current request rate
             * @example 42.7
             */
            requests_per_second: number;
            /**
             * Format: float
             * @description Uptime percentage over the last 24 hours
             * @example 99.99
             */
            uptime_percentage: number;
            /**
             * Format: float
             * @description ARC (AI Resource Credits) consumption rate
             * @example 1247.3
             */
            arc_consumption: number;
        };
        ComponentDetail: components["schemas"]["Component"] & {
            /** @description Recent events related to this component */
            events?: components["schemas"]["Event"][];
        };
        Event: {
            /**
             * @description Unique event identifier
             * @example evt_20251229_001
             */
            id: string;
            /**
             * @description Event type
             * @example success
             * @enum {string}
             */
            type: "success" | "failure" | "warning" | "info";
            /**
             * @description Event title
             * @example Component health check passed
             */
            title: string;
            /**
             * @description Detailed event description
             * @example All health metrics within normal parameters
             */
            description?: string;
            /**
             * Format: date-time
             * @description ISO8601 timestamp
             * @example 2025-12-29T20:45:00Z
             */
            timestamp: string;
            /**
             * @description Component ID this event relates to
             * @example core-substrate-hive-mind
             */
            component: string;
            /**
             * @description Agent that generated this event (if applicable)
             * @example atlas-1
             */
            agent?: string;
        };
        Error: {
            /**
             * @description Error code
             * @example NOT_FOUND
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Component not found
             */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "NOT_FOUND",
                 *       "message": "Component not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getComponents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        components?: components["schemas"]["Component"][];
                    };
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getComponentById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the component */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
