/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/battlefield/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all batches
         * @description Returns a list of all batches with their current status and progress
         */
        get: operations["getBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battlefield/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all agents
         * @description Returns a list of all agents with their current status and health
         */
        get: operations["getAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battlefield/threats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all threats
         * @description Returns a list of detected threats with severity and resolution status
         */
        get: operations["getThreats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BatchesResponse: {
            batches: components["schemas"]["Batch"][];
        };
        Batch: {
            /**
             * @description Unique batch identifier
             * @example BATCH-GEN-008
             */
            id: string;
            /**
             * @description Batch title
             * @example API Contracts for God Mode Integration
             */
            title: string;
            /**
             * @description Current batch status
             * @example in_progress
             * @enum {string}
             */
            status: "proposed" | "approved" | "in_progress" | "verifying" | "complete";
            /**
             * @description Batch priority level
             * @example P0
             * @enum {string}
             */
            priority: "P0" | "P1" | "P2";
            /**
             * @description Agent assigned to this batch
             * @example atlas-1
             */
            assigned_agent: string;
            /**
             * Format: float
             * @description Completion percentage (0-100)
             * @example 45.5
             */
            progress: number;
            /**
             * Format: date-time
             * @description ISO8601 timestamp of batch creation
             * @example 2025-12-28T10:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description ISO8601 timestamp of last update
             * @example 2025-12-29T20:45:00Z
             */
            updated_at: string;
            /**
             * @description Batch description
             * @example Define OpenAPI specs for God Mode ↔ Genesis Backend integration
             */
            description?: string;
            /**
             * Format: float
             * @description Estimated hours to complete
             * @example 8
             */
            estimated_hours?: number;
            /**
             * @description IDs of dependent batches
             * @example [
             *       "BATCH-GEN-007"
             *     ]
             */
            dependencies?: string[];
        };
        AgentsResponse: {
            agents: components["schemas"]["Agent"][];
        };
        Agent: {
            /**
             * @description Unique agent identifier
             * @example atlas-1
             */
            id: string;
            /**
             * @description Agent name
             * @example Atlas 1 (Backend)
             */
            name: string;
            /**
             * @description Agent version
             * @example 1.2.0
             */
            version: string;
            /**
             * @description Current agent status
             * @example working
             * @enum {string}
             */
            status: "working" | "idle" | "offline";
            /**
             * @description Current task being executed
             * @example BATCH-GEN-008: Creating OpenAPI specifications
             */
            current_task?: string | null;
            /**
             * Format: float
             * @description Agent health percentage (0-100)
             * @example 100
             */
            health: number;
            /**
             * Format: float
             * @description Current ARC consumption rate
             * @example 2547.8
             */
            arc_consumption: number;
            /**
             * Format: date-time
             * @description ISO8601 timestamp of last activity
             * @example 2025-12-29T20:45:00Z
             */
            last_active?: string;
        };
        ThreatsResponse: {
            threats: components["schemas"]["Threat"][];
        };
        Threat: {
            /**
             * @description Unique threat identifier
             * @example threat_20251229_001
             */
            id: string;
            /**
             * @description Threat type
             * @example drift
             * @enum {string}
             */
            type: "drift" | "performance" | "security";
            /**
             * @description Threat severity level
             * @example high
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low";
            /**
             * @description Threat title
             * @example Context drift detected in Hive Mind
             */
            title: string;
            /**
             * @description Detailed threat description
             * @example Agent context hash mismatch detected. Potential stale context.
             */
            description: string;
            /**
             * @description Source of the threat detection
             * @example shadow-protocol
             */
            source: string;
            /**
             * Format: date-time
             * @description ISO8601 timestamp when threat was detected
             * @example 2025-12-29T20:30:00Z
             */
            timestamp: string;
            /**
             * @description Whether the threat has been resolved
             * @example false
             */
            resolved: boolean;
            /**
             * Format: date-time
             * @description ISO8601 timestamp when threat was resolved
             * @example null
             */
            resolved_at?: string | null;
            /**
             * @description List of affected component IDs
             * @example [
             *       "core-substrate-hive-mind"
             *     ]
             */
            affected_components?: string[];
        };
        Error: {
            /**
             * @description Error code
             * @example BAD_REQUEST
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid query parameter
             */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "BAD_REQUEST",
                 *       "message": "Invalid query parameter"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBatches: {
        parameters: {
            query?: {
                /** @description Filter batches by status */
                status?: "proposed" | "approved" | "in_progress" | "verifying" | "complete";
                /** @description Filter batches by priority */
                priority?: "P0" | "P1" | "P2";
                /** @description Filter batches by assigned agent */
                agent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAgents: {
        parameters: {
            query?: {
                /** @description Filter agents by status */
                status?: "working" | "idle" | "offline";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getThreats: {
        parameters: {
            query?: {
                /** @description Filter threats by type */
                type?: "drift" | "performance" | "security";
                /** @description Filter threats by severity */
                severity?: "critical" | "high" | "medium" | "low";
                /** @description Filter by resolution status */
                resolved?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreatsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
