/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/constitution/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system events
         * @description Returns a paginated list of system events with optional filtering
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/constitution/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get constitution articles
         * @description Returns all articles of the ArmadaOS Constitution
         */
        get: operations["getArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EventsResponse: {
            events: components["schemas"]["Event"][];
            /**
             * @description Cursor for next page of results (null if no more pages)
             * @example eyJpZCI6ImV2dF8yMDI1MTIyOV8wNTAiLCJ0cyI6MTczNTUwMzYwMH0=
             */
            next_cursor: string | null;
        };
        Event: {
            /**
             * @description Unique event identifier
             * @example evt_20251229_001
             */
            id: string;
            /**
             * @description Event type
             * @example success
             * @enum {string}
             */
            type: "success" | "failure" | "warning" | "info";
            /**
             * @description Event title
             * @example Batch GEN-007 completed successfully
             */
            title: string;
            /**
             * @description Detailed event description
             * @example Monitoring and observability infrastructure deployed
             */
            description?: string;
            /**
             * Format: date-time
             * @description ISO8601 timestamp
             * @example 2025-12-29T20:45:00Z
             */
            timestamp: string;
            /**
             * @description Component ID this event relates to
             * @example core-substrate-hive-mind
             */
            component: string;
            /**
             * @description Agent that generated this event
             * @example atlas-1
             */
            agent?: string;
            /**
             * @description Additional event metadata
             * @example {
             *       "batch_id": "BATCH-GEN-007",
             *       "commit_hash": "6af50082"
             *     }
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        ArticlesResponse: {
            articles: components["schemas"]["Article"][];
        };
        Article: {
            /**
             * @description Unique article identifier
             * @example article-001
             */
            id: string;
            /**
             * @description Article number
             * @example 1
             */
            number: number;
            /**
             * @description Article title
             * @example The First Law
             */
            title: string;
            /**
             * @description Full article content (Markdown)
             * @example Nothing is real until it's in GitHub. You did not complete a task until GitHub reflects it...
             */
            content: string;
            /**
             * Format: date-time
             * @description ISO8601 timestamp of last amendment
             * @example 2025-12-15T10:00:00Z
             */
            last_amended: string;
            /**
             * @description Article category
             * @example Core Principles
             */
            category?: string;
            /**
             * @description Article tags
             * @example [
             *       "github",
             *       "verification",
             *       "core"
             *     ]
             */
            tags?: string[];
        };
        Error: {
            /**
             * @description Error code
             * @example BAD_REQUEST
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid date format
             */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "BAD_REQUEST",
                 *       "message": "Invalid query parameter"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEvents: {
        parameters: {
            query?: {
                /** @description Filter events by component ID */
                component?: string;
                /** @description Filter events by type */
                type?: "success" | "failure" | "warning" | "info";
                /** @description Filter events by agent */
                agent?: string;
                /** @description Start date for event range (ISO8601) */
                from?: string;
                /** @description End date for event range (ISO8601) */
                to?: string;
                /** @description Maximum number of events to return */
                limit?: number;
                /** @description Pagination cursor for next page */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getArticles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlesResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
