/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/nexus/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send chat message to Nexus
         * @description Send a message to Nexus AI and receive a complete response
         */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nexus/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send chat message with streaming response
         * @description Send a message to Nexus AI and receive a streaming response (Server-Sent Events)
         */
        post: operations["sendChatMessageStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nexus/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get chat history
         * @description Retrieve chat history for the current session
         */
        get: operations["getChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatRequest: {
            /**
             * @description User message to send to Nexus
             * @example What's the current health of the Hive Mind component?
             */
            message: string;
            context?: components["schemas"]["ChatContext"];
            /**
             * @description Session ID for conversation continuity
             * @example session_20251229_001
             */
            session_id?: string;
        };
        /** @description Additional context about the user's current view */
        ChatContext: {
            /**
             * @description Current lens the user is viewing
             * @example architecture
             * @enum {string}
             */
            current_lens?: "architecture" | "constitution" | "battlefield";
            /**
             * @description Currently selected component ID (if any)
             * @example core-substrate-hive-mind
             */
            selected_component?: string;
            /**
             * @description Currently selected batch ID (if any)
             * @example BATCH-GEN-008
             */
            selected_batch?: string;
            /**
             * @description Currently selected event ID (if any)
             * @example evt_20251229_001
             */
            selected_event?: string;
        };
        ChatResponse: {
            /**
             * @description Nexus AI response text
             * @example The Hive Mind component is currently healthy with 98.5% health score. All metrics are within normal parameters.
             */
            response: string;
            /**
             * @description Type of response provided by Nexus
             * @example interpret
             * @enum {string}
             */
            type: "guide" | "interpret" | "challenge" | "general";
            /**
             * @description Referenced components, events, or batches
             * @example [
             *       "core-substrate-hive-mind",
             *       "evt_20251229_001"
             *     ]
             */
            sources?: string[];
            /**
             * @description Suggested follow-up questions
             * @example [
             *       "What are the dependencies of Hive Mind?",
             *       "Show me recent events for this component"
             *     ]
             */
            suggestions?: string[];
            /**
             * @description Session ID for this conversation
             * @example session_20251229_001
             */
            session_id?: string;
        };
        /** @description Server-Sent Event chunk for streaming responses */
        StreamChunk: {
            /**
             * @description Individual token in the streaming response
             * @example The
             */
            token?: string;
            /**
             * @description Whether this is the final chunk
             * @example false
             */
            done?: boolean;
            /**
             * @description Type of response (only present in final chunk)
             * @example interpret
             * @enum {string}
             */
            type?: "guide" | "interpret" | "challenge" | "general";
            /**
             * @description Referenced sources (only present in final chunk)
             * @example [
             *       "core-substrate-hive-mind"
             *     ]
             */
            sources?: string[];
        };
        ChatHistoryResponse: {
            messages: components["schemas"]["ChatMessage"][];
            /**
             * @description Session ID for this conversation
             * @example session_20251229_001
             */
            session_id: string;
        };
        ChatMessage: {
            /**
             * @description Unique message identifier
             * @example msg_20251229_001
             */
            id: string;
            /**
             * @description Message sender role
             * @example user
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * @description Message content
             * @example What's the current health of the Hive Mind component?
             */
            content: string;
            /**
             * Format: date-time
             * @description ISO8601 timestamp
             * @example 2025-12-29T20:45:00Z
             */
            timestamp: string;
            /**
             * @description Response type (only for assistant messages)
             * @example interpret
             * @enum {string}
             */
            type?: "guide" | "interpret" | "challenge" | "general";
        };
        Error: {
            /**
             * @description Error code
             * @example BAD_REQUEST
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Message cannot be empty
             */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "BAD_REQUEST",
                 *       "message": "Invalid request body"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    sendChatMessageStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful streaming response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamChunk"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getChatHistory: {
        parameters: {
            query?: {
                /** @description Session ID to retrieve history for (defaults to current session) */
                session_id?: string;
                /** @description Maximum number of messages to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
