/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system status
         * @description Returns overall system status and key metrics for the header status bar
         */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed system health
         * @description Returns detailed health information for all system components
         */
        get: operations["getSystemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system metrics
         * @description Returns detailed system metrics over a time range
         */
        get: operations["getSystemMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemStatus: {
            /**
             * @description Overall system status
             * @example optimal
             * @enum {string}
             */
            status: "optimal" | "degraded" | "critical";
            /**
             * Format: float
             * @description Average CPU usage percentage across all nodes
             * @example 42.5
             */
            cpu_usage: number;
            /**
             * Format: float
             * @description Average memory usage percentage across all nodes
             * @example 67.3
             */
            memory_usage?: number;
            /**
             * Format: float
             * @description Average network latency in milliseconds
             * @example 12.4
             */
            network_latency: number;
            /**
             * @description Number of batches currently in progress
             * @example 2
             */
            active_batches: number;
            /**
             * @description Number of agents currently online
             * @example 2
             */
            online_agents: number;
            /**
             * @description Total number of registered agents
             * @example 3
             */
            total_agents: number;
            /**
             * @description Number of unresolved threats
             * @example 0
             */
            active_threats: number;
            /**
             * Format: float
             * @description System uptime in seconds
             * @example 2592000
             */
            uptime?: number;
            /**
             * Format: date-time
             * @description ISO8601 timestamp of last status update
             * @example 2025-12-29T20:45:00Z
             */
            last_updated?: string;
        };
        SystemHealth: {
            /**
             * Format: float
             * @description Overall system health score (0-100)
             * @example 98.7
             */
            overall_health: number;
            components: components["schemas"]["ComponentHealth"][];
            /**
             * Format: date-time
             * @description ISO8601 timestamp of last health check
             * @example 2025-12-29T20:45:00Z
             */
            last_updated?: string;
        };
        ComponentHealth: {
            /**
             * @description Component identifier
             * @example core-substrate-hive-mind
             */
            id: string;
            /**
             * @description Component name
             * @example Hive Mind
             */
            name: string;
            /**
             * Format: float
             * @description Component health score (0-100)
             * @example 98.5
             */
            health: number;
            /**
             * @description Component status
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "down";
            /**
             * @description Health status message
             * @example All systems operational
             */
            message?: string;
        };
        SystemMetrics: {
            /**
             * Format: date-time
             * @description Start time of metrics range
             * @example 2025-12-29T00:00:00Z
             */
            from: string;
            /**
             * Format: date-time
             * @description End time of metrics range
             * @example 2025-12-29T23:59:59Z
             */
            to: string;
            /**
             * @description Aggregation interval
             * @example 5m
             */
            interval: string;
            data_points: components["schemas"]["MetricDataPoint"][];
        };
        MetricDataPoint: {
            /**
             * Format: date-time
             * @description ISO8601 timestamp of this data point
             * @example 2025-12-29T20:45:00Z
             */
            timestamp: string;
            /**
             * Format: float
             * @description CPU usage percentage
             * @example 42.5
             */
            cpu_usage: number;
            /**
             * Format: float
             * @description Memory usage percentage
             * @example 67.3
             */
            memory_usage: number;
            /**
             * Format: float
             * @description Network latency in milliseconds
             * @example 12.4
             */
            network_latency: number;
            /**
             * Format: float
             * @description Total requests per second
             * @example 1247.8
             */
            requests_per_second?: number;
            /**
             * @description Number of active connections
             * @example 342
             */
            active_connections?: number;
        };
        Error: {
            /**
             * @description Error code
             * @example BAD_REQUEST
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid time range
             */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "BAD_REQUEST",
                 *       "message": "Invalid query parameter"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getSystemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealth"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getSystemMetrics: {
        parameters: {
            query?: {
                /** @description Start time for metrics (ISO8601) */
                from?: string;
                /** @description End time for metrics (ISO8601) */
                to?: string;
                /** @description Aggregation interval */
                interval?: "1m" | "5m" | "15m" | "1h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemMetrics"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
